### ISSUE TITLE
Startup error in Arch Linux

### ISSUE THREAD

**Issue by avamk** [spantaleev/sftpman-gtk#5] opened 2016-07-30 13:39 UTC
Hello,

After installing sftpman-gtk and sftpman in Arch Linux, the GUI gives the error:

> Mount path '/mnt/sshfs' doesn't exist or is not writable by the current user.

What do I do to fix this? Thank you.

**Comment by TomaszGasior** [comment] 2016-08-24 23:39
You should have permissions to write in /mnt/sshfs directory. By default this directory has owner „root” and group „users”. You should add your account to „users” group to give permissions in /mnt/sshfs. Run in terminal command: `sudo usermod -aG users login`. As „login” put your username.

**Comment by avamk** [comment] 2016-08-25 09:16
Yes, that worked. Thank you!

Unfortunately after setting up a remote share to mount, I keep getting a "connection reset by peer" error, even though using ssh in the terminal works...

**Comment by TomaszGasior** [comment] 2016-08-25 10:13
I have the same problem. In optional dependences of archlinux package I can find „openssh-askpass: allows you to enter passwords during mounting [install requires session restart]”. Unfortunately SftpmanGTK shows „connection reset by peer” error even when I have this package installed.

**Comment by avamk** [comment] 2016-08-25 14:57
Glad I'm not the only one with this problem. Should I start a new issue? Is there some diagnostic actions I can take to help troubleshoot it?

**Comment by spantaleev** [comment] 2016-08-25 21:31
Yes, it is a separate issue and I have also come across this (when authentication happens using passwords).

For some reason, in such a case, no prompt window comes up and it gets stuck. Is this what you're observing as well?

**Comment by avamk** [comment] 2016-08-25 23:21
I do get a prompt window saying connection reset by peer which I can
click OK for. Are you also getting connection reset by peer?

(BTW yes I'm also trying this with password authentication)

**Comment by kamzata** [comment] 2017-02-20 05:18
Did you find any fix or workaround? I receive "Connection reset by peer" message as well, even though installed "openssh-askpass" package.

**Comment by spantaleev** [comment] 2017-02-20 06:39
If you use the `sftpman` command line app, you can do `sftpman mount <your-mount-name-here>` and it would also print the actual `sshfs` command used to connect.

You could then run that `sshfs` command manually and see what it tells you. You could possibly add some `-o sshfs_debug` option to the command, etc.

Most of the times that I've seen a `Connection reset by peer` error, it's some SSH/`sshfs` configuration error.
An askpass setup problem usually causes a GUI freeze, not a "Connection reset by peer" error.

On the other hand, if `sftpman mount <your-mount-name-here>` succeeds for you (while it fails through the GUI), it may be something else.

**Comment by kamzata** [comment] 2017-02-20 10:02
Running the command passed by `sftpman mount www` on the CLI gave the same error message:

[kamzata@pc /]$ `true && sshfs -o ssh_command='ssh -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password -o sshfs_debug'  dev@www.example.com:/var/www /mnt/sshfs/www
read: Connection reset by peer
`

but if I run the command like this it works:

[kamzata@pc /]$ `true && sshfs -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password -o sshfs_debug  dev@www.example.com:/var/www /mnt/sshfs/www
Offending key for IP in /home/kamzata/.ssh/known_hosts:7
Matching host key in /home/kamzata/.ssh/known_hosts:5
Are you sure you want to continue connecting (yes/no)? yes
dev@www.example.com's password: `

**Comment by kamzata** [comment] 2017-02-21 12:24
The problem lies in closing quotation mark of _ssh_command_ option.

`[kamzata@pc /]$ true && sshfs -o ssh_command='ssh -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password -o sshfs_debug' dev@www.example.com:/var/www /mnt/sshfs/www
`
should be

`[kamzata@pc /]$ true && sshfs -o ssh_command='ssh' -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password -o sshfs_debug dev@www.example.com:/var/www /mnt/sshfs/www
`

I made a pull request on _sftpman_ project.

**Comment by kamzata** [comment] 2017-02-24 13:28
@spantaleev as you said, my mistake. I put wrongly _sshfs_debug_ option inside ssh_command quotes. So the follow command works:

```
[kamzata@pc /]$ true && sshfs -o ssh_command='ssh -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password' -o sshfs_debug dev@www.example.com:/var/www /mnt/sshfs/www
SSHFS version 2.8
dev@www.example.com's password:

```

but in order to use sftpman I have to setup it as follow:

```
[kamzata@pc /]$ sftpman setup --id "www.example.com" --host "www.example.com" --user "dev" --mount_point "/var/www" --port 12345 --auth_method=password
```
then using it like this:

```
[kamzata@pc /]$ sftpman ls available
www.example.com
[kamzata@pc /]$ sftpman mount www.example.com
[kamzata@pc /]$ sftpman ls mounted
www.example.com
```

So sftpman does work. Using `sftpman setup` and then `sftpman mount` command on the CLI make the share visible and mounted also in the GUI. But once mounted it through the CLI if I try to unmount and remount it through the GUI it gives me the same error as before.

![screen1](https://cloud.githubusercontent.com/assets/1103317/23305109/7a9e72ee-fa9d-11e6-9dda-aba33712b1fc.png)

**Comment by spantaleev** [comment] 2017-02-24 13:33
The `sftpman` CLI asks you for a password every time?

If you are to paste that "Mount command" (`true && sshfs ..`) into the terminal, does it go through? (by the way, before it can work, you'd have to create the mount directory manually.. `mkdir /mnt/sshfs/your-mount-name`)

**Comment by kamzata** [comment] 2017-02-24 13:54
> The sftpman CLI asks you for a password every time?

Yes, it does. `sftpman` asks for the password every time a run `sftpman mount www.example.com`:

```
[kamzata@pc /]$ sftpman mount www.example.com
dev@www.example.com's password: 
```

> If you are to paste that "Mount command" (true && sshfs ..) into the terminal, does it go through? (by the way, before it can work, you'd have to create the mount directory manually.. mkdir /mnt/sshfs/your-mount-name)

Yes, it does. And yes again, before I run this command I have to manually create the folder and assign it current user's ownership and permissions.

```
[kamzata@pc /]$ sudo mkdir /mnt/sshfs/www
[kamzata@pc /]$ sudo chown kamzata:kamzata /mnt/sshfs/www
[kamzata@pc /]$ chmod 777 /mnt/sshfs/www
[kamzata@pc /]$ true && sshfs -o ssh_command='ssh -o ConnectTimeout=8 -p 12345 -o PreferredAuthentications=password' -o sshfs_debug dev@www.example.com:/var/www /mnt/sshfs/www
SSHFS version 2.8
dev@www.example.com's password:
```

**Comment by spantaleev** [comment] 2017-02-24 14:06
I see. So it looks like the instant (is it instant?) `Connection reset by peer` problem is caused by the GUI not being able to ask for a password.

Perhaps `openssh-askpass` is not working as we expect. I am not completely sure how it's supposed to get triggered and why it doesn't in your case.. Although I have seen similar problems (mostly just program hanging) in some environments.

Do you have another program you could try? Perhaps `x11-ssh-askpass`. Maybe you need to restart your X session before it (potentially) works.

**Comment by kamzata** [comment] 2017-02-24 14:30
> I see. So it looks like the instant (is it instant?) Connection reset by peer problem is caused by the GUI not being able to ask for a password.

I was just editing my previous answer to write about this. Yes, it shows up instantly.

> Perhaps openssh-askpass is not working as we expect. I am not completely sure how it's supposed to get triggered and why it doesn't in your case.. Although I have seen similar problems (mostly just program hanging) in some environments.
Do you have another program you could try? Perhaps x11-ssh-askpass. Maybe you need to restart your X session before it (potentially) works.

Using `x11-ssh-askpass` **works** in spite of really old-fashioned GUI style and even though it asks every time for the password. Do you use this?

**Comment by spantaleev** [comment] 2017-02-24 17:43
Yes, I'm using `x11-ssh-askpass` and it works well for me too (although I don't use password-based authentication).

**Comment by kamzata** [comment] 2017-02-25 01:24
> Yes, I'm using x11-ssh-askpass and it works well for me too (although I don't use password-based authentication).

Thank you so much for your support! Really useful app.

**Comment by spantaleev** [comment] 2017-02-25 07:46
Thank you and glad to hear `sftpman` is useful to you! 👍 

I'll close this issue now.

**Closed as completed by spantaleev** 2017-02-25 07:46 UTC
